services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - microservicio_go_mongo_net
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio-go
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - microservicio_go_mongo_net

volumes:
  mongo_data:

networks:
  microservicio_go_mongo_net:
    driver: bridge
